build_task:
  container:
    image: maven:latest
  maven_cache:
    folder: ~/.m2/repository 
  build_script:
    - mvn clean install
  artifact_cache:
    make_folder_script:
      - mkdir -p ~/build_artifacts
    folder: ~/build_artifacts
    fingerprint_script:
      - ls ~/build_artifacts
    populate_script:
      - cp */target/*.jar ~/build_artifacts

plugin_qa_task:
  depends_on:
    - build
  container:
    image: maven:latest
  maven_cache:
    folder: ~/.m2/repository
  submodules_script:
    - git submodule update --init
  artifact_cache:
    folder: ~/build_artifacts
    fingerprint_script:
      - ls ~/build_artifacts
    # populate_script:
    #   - cp */target/*.jar ~/build_artifacts
  get_build_artifacts_script:
    - mkdir -p external-reports/target; cp ~/build_artifacts/external-reports-*.jar external-reports/target
    - mkdir -p java-checks/target; cp ~/build_artifacts/java-checks-*.jar java-checks/target
    - mkdir -p java-frontend/target; cp ~/build_artifacts/java-frontend-*.jar java-frontend/target
    - mkdir -p java-jsp/target; cp ~/build_artifacts/java-jsp-*.jar java-jsp/target
    - mkdir -p java-surefire/target; cp ~/build_artifacts/java-surefire-*.jar java-surefire/target
    - mkdir -p jdt/target; cp ~/build_artifacts/jdt-*.jar jdt/target
    - mkdir -p sonar-java-plugin/target; cp ~/build_artifacts/sonar-java-plugin-*.jar sonar-java-plugin/target
  qa_script:
    - echo "Ready to Run Integration Tests..."
